### ISSUE TITLE
The type or namespace name 'Framework' does not exist in the namespace 'NUnit'

### ISSUE THREAD

**Issue by YMIndustries** [nunit/dotnet-test-nunit#110]
Hi,

I'm doing my best to try to port a library to .Net Core ([YMIndustries/tesseract](https://github.com/YMIndustries/tesseract))

It uses NUnit for the tests and I've run into an issue when trying to use dotnet-test-nunit to run these. I installed dotnet-test-nunit (3.4.0-beta-3) via NuGet and it seems to kinda work, because when I type `using NUnit.` IntelliSense suggests Engine, Options and Runner. It doesn't suggest Framework though, and putting `using NUnit.Framework;` results in the error "The type or namespace name 'Framework' does not exist in the namespace 'NUnit'".

I'm wondering what I've done wrong. I'm using Visual Studio 2017 with .NET Core 1.0.

Thanks,
Josh

**Comment by rprouse** [comment]
The `dotnet-test-nunit` adapter does not support VS 2017. Microsoft changed the way test adapters work with the tooling that ships with 2017. See #108 for more info.

For now, the best bet is to make your tests self executing using NUnitLite. See http://www.alteridem.net/2015/11/04/testing-net-core-using-nunit-3/ for more info. It is an old post, but outlines the basic steps.

I am working on a solution for VS2017, so hopefully we will have a fix soon.

**Comment by YMIndustries** [comment]
Is that the same issue? They seem to have a different error message.

**Comment by rprouse** [comment]
Different error message, but this adapter will no longer work when you have 2017 installed. You are using a CSPROJ file not XPROJ/project.json right?

**Comment by CharliePoole** [comment]
Actually, your immediate error seems to be due to not referencing the nunit framework. If you fix that you'll run into the major issue cited by @rprouse.

**Comment by YMIndustries** [comment]
How can I reference the NUnit framework? If I download NUnit from NuGet it doesn't seem to work, I think because it's not compatible with .Net Core.

**Comment by CharliePoole** [comment]
You can reference the .Net Standard build. However, that won't solve your problem of running in VS2017.

**Comment by YMIndustries** [comment]
The solution to get the .Net Standard build to be recognised properly was to do a Rebuild of my project instead of a simple Build. Thanks @CharliePoole for telling me that it should work!
