### ISSUE TITLE
Add the supporting of Visual Studio Test Platform

### ISSUE THREAD

**Issue by NikolayPianikov** [nunit/dotnet-test-nunit#111]
To create NUnit test projects like [here](https://blogs.msdn.microsoft.com/visualstudioalm/2016/11/29/evolving-the-test-platform-part-3-net-core-convergence-and-cross-plat/). Also see [it](https://github.com/Microsoft/vstest)

**Comment by rprouse** [comment]
I am closing this as a duplicate of #108
