### ISSUE TITLE
NUnit test for netstandard 1.6

### ISSUE THREAD

**Issue by avikenjale** [nunit/dotnet-test-nunit#119]
I have created a .net core class library for version - netstandard 1.6, which comes with .csproj template for project and no more project.json. So I am unable to add following 2 items per project.json to .csproj file:

-testrunner
- dependency - "dotnet-test-nunit"

Please assist.

**Comment by ChrisMaddock** [comment]
Hi @avikenjale,

Microsoft deprecated this form of test adapter when the brought out the new csproj. You now need to be using the NUnit3TestAdapter pre-release NuGet package - there's more information at the link below.

http://www.alteridem.net/2017/05/04/test-net-core-nunit-vs2017/

I'll close this issue - but please ask if you hit any further problems!

**Comment by avikenjale** [comment]
Yes, After adding following references, my tests were good.

    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.0.0" />
    <PackageReference Include="NUnit" Version="3.6.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="3.8.0-alpha1" />

**Comment by avikenjale** [comment]
@ChrisMaddock , This introduced a new issue to me. I am using VS 2017 along with ReSharper 2017.x version. Earlier I was able to see ReSharper context menus under Solution - right click menus, like `Run Tests` or `Run Test Coverages`. Does these package references can interfere with ReSharper settings?

**Comment by ChrisMaddock** [comment]
@avikenjale Sorry - that's a question you'll have to ask the ReSharper team.

If you've gone from project.json -> csproj though - be aware this is an entirely different way of running tests. ReSharper would need to support it in a different way.
