### ISSUE TITLE
Can't specify bitness on command line

### ISSUE THREAD

**Issue by damageboy** [nunit/dotnet-test-nunit#123]
## Steps to reproduce
Run dotnet test on a assembly with nunit:
```
dotnet test -- TargetPlatform=x64
```

## Expected  behavior
Be able to specify bitness (x64 / x86)

## Actual behavior
Always runs on x86 in Windows by default

## Environment data
`dotnet --info` output:

```
C:\projects\junk.git\tests\Junk.Tests>dotnet --info
.NET Command Line Tools (2.0.0)

Product Information:
 Version:            2.0.0
 Commit SHA-1 hash:  cdcd1928c9

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.0.0\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

**Comment by rprouse** [comment]
1. You are using .NET Core 2.0, this repository is for the old `dotnet test` command line for the project.json format. The repo you want is the NUnit3TestAdapter.
2. I believe you are using the command line for the old xproj format, there is no TargetPlatform command line option for `dotnet test` or for the underlying `vstest.console.exe`. The VSTest command line option is `/Platform:x64`.

https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-test?tabs=netcore2x
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-vstest

I created the following test,

```c#
[Test]
public void IsRunning64Bit()
{
    unsafe
    {
        Assert.That(sizeof(IntPtr), Is.EqualTo(8));
    }
}
```

And I run it with the command line, `dotnet test` and it passes, so it is running `x64` by default. **Are you sure you don't have `Prefer 32-bit` set?

To switch the bitness that the process runs as, you have to use `dotnet vstest`. `dotnet test` used to pass extra command line options on to `vstest`, but now that I have 2.0 installed, it doesn't seem to be working.

If I switch to `dotnet vstest .\bin\Debug\netcoreapp2.0\NetCore20Tests.dll /platform:x86`, the test correctly failed for me once, but now every time I run it, it passes 😕 

The command line is correct, if I switch `/platform:x86` to `/platform:bad`, it gives the warning message `Invalid platform type:bad. Valid platform types are x86, x64 and Arm.` I can even run it as Arm and it passes which it shouldn't.

**Comment by rprouse** [comment]
I am going to move this to the NUnit vs adapter repo where it belongs. Please follow it there...

**Comment by rprouse** [comment]
Issue moved to [nunit/nunit3-vs-adapter #389](https://github.com/nunit/nunit3-vs-adapter/issues/389) via [**ZenHub**](https://www.zenhub.com/)
