### ISSUE TITLE
Failed to restore "dotnet-test-nunit" for netcoreapp1.0

### ISSUE THREAD

**Issue by alexandrnikitin** [nunit/dotnet-test-nunit#41]
Hi,

I'm following your blog post [NUnit 3 Tests for .NET Core RC2 and ASP.NET Core RC2](http://www.alteridem.net/2016/06/18/nunit-3-testing-net-core-rc2/)

But it fails to restore `dotnet-test-nunit`. I have the following log file:
```
log  : Restoring packages for C:\Projects\contrib\NSubstitute\Source\NSubstitute.Acceptance.Specs\project.json...
info :   CACHE https://api.nuget.org/v3-flatcontainer/microsoft.netcore.app/index.json
error: Package Microsoft.Extensions.Testing.Abstractions 1.0.0-preview2-003121 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.Extensions.Testing.Abstractions 1.0.0-preview2-003121 supports:
error:   - net451 (.NETFramework,Version=v4.5.1)
error:   - netstandard1.6 (.NETStandard,Version=v1.6)
error: Package Microsoft.Extensions.DependencyModel 1.0.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.Extensions.DependencyModel 1.0.0 supports:
error:   - net451 (.NETFramework,Version=v4.5.1)
error:   - netstandard1.6 (.NETStandard,Version=v1.6)
error: One or more packages are incompatible with .NETCoreApp,Version=v1.0.
info : Committing restore...
log  : Lock file has not changed. Skipping lock file write. Path: C:\Projects\contrib\NSubstitute\Source\NSubstitute.Acceptance.Specs\project.lock.json
log  : C:\Projects\contrib\NSubstitute\Source\NSubstitute.Acceptance.Specs\NSubstitute.Acceptance.Specs.xproj
log  : Restore failed in 772ms.
Errors in C:\Projects\contrib\NSubstitute\Source\NSubstitute.Acceptance.Specs\NSubstitute.Acceptance.Specs.xproj
    Package Microsoft.Extensions.Testing.Abstractions 1.0.0-preview2-003121 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.Extensions.Testing.Abstractions 1.0.0-preview2-003121 supports:
      - net451 (.NETFramework,Version=v4.5.1)
      - netstandard1.6 (.NETStandard,Version=v1.6)
    Package Microsoft.Extensions.DependencyModel 1.0.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package Microsoft.Extensions.DependencyModel 1.0.0 supports:
      - net451 (.NETFramework,Version=v4.5.1)
      - netstandard1.6 (.NETStandard,Version=v1.6)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.
```

My project.json looks like this:
```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "NSubstitute": {
      "target": "project"
    },
    "NUnit": "3.4.0",
    "dotnet-test-nunit": "3.4.0-beta-1",
    // TODO Remove when fixed in Castle
    "System.Diagnostics.TraceSource": "4.0.0-rc2-24027"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dnxcore50",
        "netcoreapp1.0",
        "portable-net45+win8"
      ],
      "dependencies": {
        "Microsoft.NETCore.App": {
          "version": "1.0.0-*",
          "type": "platform"
        }
      }
    }
  }
}
```

I seems like `netcoreapp1.0` isn't supported.

**Comment by jasonwilliams200OK** [comment]
@alexandrnikitin, this seems like the problem with your project NSubsitute, which you are probably building as part of the solution (dependency to this project) right?
If you can share the PJ of that project, we can help you figure out the issue.


Besides that there is a room for improvement in the project.json of your test project that you shared:

* `"testRunner": "nunit",` is missing
* you don't need `dnxcore50` in your `imports` list, as its a [deprecated moniker](https://github.com/dotnet/corefx/blob/96fd6fdbae3ea8c0419999d89908dfd28bcb8136/Documentation/architecture/net-platform-standard.md#deprecated-monikers).
* recursive import of `netcoreapp1.0` is redundant (I can see that it is also present in blog, but not required)

Here is the an improved version of your project.json:

```json
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "NSubstitute": {
      "target": "project"
    },
    "NUnit": "3.4.0",
    "dotnet-test-nunit": "3.4.0-beta-1",
    "System.Diagnostics.TraceSource": "4.0.0-rc2-24027"
  },

  "testRunner": "nunit",

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "portable-net45+win8"
      ],
      "dependencies": {
        "Microsoft.NETCore.App": {
          "version": "1.0.0-*",
          "type": "platform"
        }
      }
    }
  }
}
```

**Comment by jasonwilliams200OK** [comment]
You may also want to upgrade all your packages from RC2 to RTM:

`"System.Diagnostics.TraceSource": "4.0.0-rc2-24027"` will become `"System.Diagnostics.TraceSource": "4.0.0"`.
(see http://www.nuget.org/packages?q=System.Diagnostics.TraceSource)

**Comment by alexandrnikitin** [comment]
@jasonwilliams200OK Thank you for your reply. I've tried different ways but without luck.
I downloaded [the Microsoft.Extensions.DependencyModel package](https://www.nuget.org/packages/Microsoft.Extensions.DependencyModel/1.0.0) and indeed it doesn't support `netcoreapp1.0` framework only `netstandart1.6`. The same with `Microsoft.Extensions.Testing.Abstractions`

**Comment by jasonwilliams200OK** [comment]
@alexandrnikitin, can you try:

```cmd
mkdir c:\temp
cd c:\temp
mkdir test
cd test

notepad project.json
```
then paste and save:
```json
{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "Microsoft.Extensions.Testing.Abstractions": "1.0.0-preview2-003121"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "version": "1.0.0-*",
          "type": "platform"
        }
      }
    }
  }
}
```

Then execute:

```cmd
dotnet restore
```

Does it work?

I am using latest dotnet cli:

>
.NET Command Line Tools (1.0.0-preview2-003121)


and it restores here..

If you are running the same (stable) version of CLI and doesn't restore on your system, then try `dotnet restore --no-cache`.

**Comment by jasonwilliams200OK** [comment]
> it doesn't support netcoreapp1.0 framework only netstandart1.6

Note that netcoreapp1.0 supports all netstandard1.x monikers. See https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md#mapping-the-net-platform-standard-to-platforms

The real error is masked by something else. There are many issues with dotnet-cli atm. Again if you can share your other project.json (or make a dummy steps to repro) we can provide more help and get this issue to resolved state. :)

**Comment by alexandrnikitin** [comment]
Indeed, the problem was in tools. I reinstalled everything .NET Core related, Runtime, CLI and VS extension, and it worked. Thank you for the help!

Could you please mention that requirement in your blog post please. I believe I won't be the only one.

**Comment by alexandrnikitin** [comment]
@jasonwilliams200OK Surprisingly, some tests fail in Test Explorer while everything is OK via CLI. Uhh, that .NET Core. I'll try to figure out what's wrong a bit later. The branch is here if you're interested: https://github.com/alexandrnikitin/NSubstitute/tree/wip_tests

**Comment by alexandrnikitin** [comment]
@jasonwilliams200OK It seems that VS runner doesn't take `Explicit` into account while CLI does.

**Comment by jasonwilliams200OK** [comment]
@alexandrnikitin there you go https://github.com/alexandrnikitin/NSubstitute/pull/1. I have fixed all the warnings as well.
