### ISSUE TITLE
Couldn't get 'dotnet-test-nunit 3.4.0-beta-1' to work with .Net Core 1.0 bits

### ISSUE THREAD

**Issue by jcansdale** [nunit/dotnet-test-nunit#42]
When I tried installing the NuGet package, I see:

```
==========
Retrieving package 'dotnet-test-nunit 3.4.0-beta-1' from 'nuget.org'.
  GET https://www.nuget.org/api/v2/Packages(Id='dotnet-test-nunit',Version='3.4.0-beta-1')
  OK https://www.nuget.org/api/v2/Packages(Id='dotnet-test-nunit',Version='3.4.0-beta-1') 134ms
  GET https://www.nuget.org/api/v2/package/dotnet-test-nunit/3.4.0-beta-1
  OK https://www.nuget.org/api/v2/package/dotnet-test-nunit/3.4.0-beta-1 610ms
Installing dotnet-test-nunit 3.4.0-beta-1.
Installing NuGet package dotnet-test-nunit.3.4.0-beta-1.
Successfully installed 'dotnet-test-nunit 3.4.0-beta-1' to ClassLibrary6
Executing nuget actions took 1.24 sec
========== Finished ==========
Time Elapsed: 00:00:01.5367951
PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\git
C:\Program Files\dotnet\dotnet.exe restore "c:\scratch\temp\.vs\restore.dg"
log  : Restoring packages for c:\scratch\temp\ClassLibrary6\project.json...
error: Package dotnet-test-nunit 3.4.0-beta-1 is not compatible with netstandard1.6 (.NETStandard,Version=v1.6). Package dotnet-test-nunit 3.4.0-beta-1 supports:
error:   - net451 (.NETFramework,Version=v4.5.1)
error:   - netcoreapp1.0 (.NETCoreApp,Version=v1.0)
error: One or more packages are incompatible with .NETStandard,Version=v1.6.
log  : Writing lock file to disk. Path: c:\scratch\temp\ClassLibrary6\project.lock.json
log  : c:\scratch\temp\ClassLibrary6\ClassLibrary6.xproj
log  : Restore failed in 1106ms.
Errors in c:\scratch\temp\ClassLibrary6\ClassLibrary6.xproj
    Package dotnet-test-nunit 3.4.0-beta-1 is not compatible with netstandard1.6 (.NETStandard,Version=v1.6). Package dotnet-test-nunit 3.4.0-beta-1 supports:
      - net451 (.NETFramework,Version=v4.5.1)
      - netcoreapp1.0 (.NETCoreApp,Version=v1.0)
    One or more packages are incompatible with .NETStandard,Version=v1.6.
============
```

Is it not compatible with .NETStandard v1.6?

Thanks,
Jamie.

**Comment by FransBouma** [comment]
Same here. Tried to use this guide: http://www.alteridem.net/2016/06/18/nunit-3-testing-net-core-rc2/ but it in the end gives: 
error: Package dotnet-test-nunit 3.4.0-beta-1 is not compatible with netstandard1.6 (.NETStandard,Version=v1.6). Package dotnet-test-nunit 3.4.0-beta-1 supports:
error:   - net451 (.NETFramework,Version=v4.5.1)
error:   - netcoreapp1.0 (.NETCoreApp,Version=v1.0)
error: One or more packages are incompatible with .NETStandard,Version=v1.6.

I think it's the NetCoreApp dependency, as it should be NET standard now.

**Comment by jasonwilliams200OK** [comment]
> the tests have to be in an application, not in a library, as they invoke a main

Exactly, the consumer test app just need to target netcoreapp1.0. Just like: https://github.com/nunit/dotnet-test-nunit/tree/release/3.4.0#projectjson. No need to emitEntryPoint to render it as a vetted console app etc.

**Comment by jcansdale** [comment]
@FransBouma, @jasonwilliams200OK,

> (edit) Ah I see what's the problem: the guide is wrong, the tests have to be in an application, not in a library, as they invoke a main. So the tests have to be in a console app, not a class lib

Wow, that's going to confuse people! You'd think 'dotnet-test-nunit' would have the entry point and it load the test assembly. Converting my test project to a console app does indeed seem to make it works.

Thanks for the tip.

**Comment by jasonwilliams200OK** [comment]
> that's going to confuse people

To un-confuse people, they have written this doc: https://github.com/dotnet/corefx/blob/f06d07b/Documentation/architecture/net-core-applications.md#faq :smile:

**Comment by CharliePoole** [comment]
Good grief!

**Comment by jcansdale** [comment]
> https://github.com/dotnet/corefx/blob/f06d07b/Documentation/architecture/net-core-applications.md#faq :smile:

I think I'll need to read that a few times before I understand it! :confused:

So, .NETStandard is a source target platform as opposed to .NETCoreApp and .NETFramework which are binary target platforms. Am I understanding that correctly?

**Comment by jasonwilliams200OK** [comment]
In project.json, so far we have these options for `frameworks`:

* netcoreapp1.0  (exe type app, including test)
* netstandard1.0, netstandard1.3, netstandard1.4, netstandard1.5 and/or netstandard1.6 (lib type app)

and/or the old: net462, net461, net460, net452, net451, net45, net4, net35, net30, net20

**Comment by FransBouma** [comment]
> So, .NETStandard is a source target platform as opposed to .NETCoreApp and .NETFramework which are binary target platforms. Am I understanding that correctly?

Let's ask @onovotny, as he seems to be the only human being alive who clearly understands this standard voodoo. (I thought it was simple, but I only knew about netstandardx.y; with .netcoreapp standards the matrix expands... )

**Comment by jasonwilliams200OK** [comment]
"Learning by doing" is the approach I used to convert over 25 projects so far and validated over 4 different operating systems. :wink: 

Also I use search on this https://github.com/microsoft/dotnet-apiport as your first weapon of choice, then corefx itself, then https://docs.microsoft.com/en-us/dotnet/core/api/index and finally good ol' google.

**Comment by onovotny** [comment]
Think of it this way -- `netcoreapp` is for exe's and `netstandard` is for libraries. You can see how they line-up here:
https://docs.microsoft.com/en-us/dotnet/articles/standard/library

At present, `netcoreapp1.0` supports up to `netstandard1.6`. So you target your libraries for `netstandard`.

Keep in mind that just because a library targets `netstandard` doesn't automatically mean it'll work on all runtimes. For some things like `System.Threading.Thread`, it needs a runtime support, so it works on Xamarin, `netcoreapp` and desktop framework, but not UWP (yet). 

One way to be sure is that things in `NETStandard.Library` will work everywhere, but other packages outside of that may not ... you need to check if you need to use them.

**Comment by onovotny** [comment]
FWIW, you an can see how it's done for xunit here:
https://github.com/xunit/dotnet-test-xunit/blob/master/src/dotnet-test-xunit/project.json

**Comment by onovotny** [comment]
Also, looking at the error above, I wonder if the submitter has the latest CLI tooling. A few things to try:

1. Remove all verisons of the SDK tooling
2. run `nuget locals all -clear` to nuke all local caches
3. Reinstall the preview 2 SDK

**Comment by FransBouma** [comment]
Thanks Oren :)

**Comment by jcansdale** [comment]
Thanks for the explanation, @onovotny. I've done the 3 steps you suggested. I'm still getting an error when I try to use a Class Library project.

Here is what I tried:

1) Using preview 2 in VS2015, create new .NET Core 'Class Library' and 'Console Application' projects.
2) Add the 'dotnet.test.nunit' NuGet package to both.

The 'Console Application' builds just fine, but the 'Class Library' gives the following error:

1>------ Build started: Project: ClassLibrary1, Configuration: Debug Any CPU ------
1>  C:\Program Files\dotnet\dotnet.exe build "c:\scratch\temp\coretests2\ConsoleApp1\src\ClassLibrary1" --configuration Debug --no-dependencies
1>  Project ClassLibrary1 (.NETStandard,Version=v1.6) will be compiled because expected outputs are missing
1>  Compiling ClassLibrary1 for .NETStandard,Version=v1.6
1>c:\scratch\temp\coretests2\ConsoleApp1\src\ClassLibrary1\project.json(5,39): error NU1002: The dependency dotnet-test-nunit 3.4.0-beta-1 does not support framework .NETStandard,Version=v1.6.
1>  Compilation failed.
1>      0 Warning(s)
1>      1 Error(s)
1>  Time elapsed 00:00:00.0364477
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Here are the project.json files:

========= Console Application =========

{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true
  },

  "dependencies": {
    "dotnet-test-nunit": "3.4.0-beta-1",
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0"
    }
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": "dnxcore50"
    }
  }
}

========= 'Class Library' =========
{
  "version": "1.0.0-*",

  "dependencies": {
    "dotnet-test-nunit": "3.4.0-beta-1",
    "NETStandard.Library": "1.6.0"
  },

  "frameworks": {
    "netstandard1.6": {
      "imports": "dnxcore50"
    }
  }
}

==============

Any idea why it might be failing?

Thanks,
Jamie.

**Comment by jasonwilliams200OK** [comment]
@jcansdale, try:

::: <del>Console</del> Test Application :::

```json
{
  "version": "1.0.0-*",

  "dependencies": {
    "NAME_OF_YOUR_LIBRARY_APP": {
      "target": "project"
    },
    "dotnet-test-nunit": "3.4.0-beta-1",
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0"
    }
  },

  "frameworks": {
    "imports": "dotnet5.6",
  }
}
```

========= 'Class Library' =========

```json
{
  "version": "1.0.0-*",

  "dependencies": {
    "NETStandard.Library": "1.6.0"
  },

  "frameworks": {
    "netstandard1.6": { }
  }
}
```
(i.e. no need for test framework dependency here and imports array is also redundant unless you need it for some other dep)

**Comment by jasonwilliams200OK** [comment]
@jcansdale did you get a chance to try that solution? Is there anything else required here?

**Comment by jcansdale** [comment]
@jasonwilliams200OK This solution does indeed work. What I was trying to get my head around is what the difference between "netcoreapp1.0" and "netstandard1.6" projects is.

Is seems "Microsoft.NETCore.App" projects also generate ".runtimeconfig.dev.json" and  ".runtimeconfig.json" file, which are also important. I don't know which part of the 'project.json' file tells the build to generate them. Maybe @onovotny can tell us?

**Comment by rprouse** [comment]
I am going to close this issue as a question. Please reopen if you feel that is a mistake or if there is something we can do in the runner to prevent this.

**Comment by hanssens** [comment]
> Note: being aware that this issue is closed, I'm still adding my endeavours to this thread for future reference

I had the same problem, following the blog post to the latter, only with some different libraries which were referenced by: 

* NUnit.Portable.Agent
* Microsoft.DiaSymReader
* Microsoft.DiaSymReader.Native.

Basically, what I did was **install the erroring packages manually** with Install-Package. 
This fixed it for me. The result was the following project.json:

```
{
  "version": "1.0.0-*",

  "dependencies": {
    "MyTestLibrary": {
      "target": "project"
    },
    "NUnit.Portable.Agent": "3.4.0-beta-1",
    "NUnit": "3.4.1",
    "Microsoft.DiaSymReader.Native": "1.5.0-beta1",
    "Microsoft.DiaSymReader": "1.0.8",
    "dotnet-test-nunit": "3.4.0-beta-1"
  },

  "testRunner": "nunit",

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "portable-net45+win8"
      ],
      "dependencies": {
        "Microsoft.NETCore.App": {
          "version": "1.0.0-*",
          "type": "platform"
        }
      }
    }
  }
}
```

With this, it worked running in the Visual Studio Test Explorer window but also on a Mac using `dotnet test`. 👍

**Comment by UweKeim** [comment]
I've succeeded with @hanssens suggestion above.

My updated "project.json" looks like:

```
{
  "version": "1.0.0-*",

  "dependencies": {
    "dotnet-test-nunit": "3.4.0-beta-2",
    "Microsoft.DiaSymReader": "1.0.8",
    "Microsoft.DiaSymReader.Native": "1.5.0-beta1",
    "NUnit": "3.4.1",
    "NUnit.Portable.Agent": "3.4.0-beta-2",
    "MyTestLibrary": "1.0.0-*"
  },

  "testRunner": "nunit",

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "portable-net45+win8"
      ],
      "dependencies": {
        "Microsoft.NETCore.App": {
          "version": "1.0.0-*",
          "type": "platform"
        }
      }
    }
  }
}
```

I had one more obstacle:

I've configured several NuGet sources in VS 2015 (a NuGet server in our local network). If they were active, the package download/restore failed, even though all packages were shown in the NuGet Package Manager window.

The solution was to uncheck my local NuGet servers:

![image](https://cloud.githubusercontent.com/assets/415439/17633904/1c14819e-60d0-11e6-9d89-cfa3e12686ff.png)

Maybe this helps someone, too.

**Comment by CharliePoole** [comment]
Good tip! I think I've seen that behavior as well. A problem with a source that is _not selected_ causes the install or update to fail.

**Comment by jasonwilliams200OK** [comment]
@UweKeim, thanks for the tip!
One minor nitpick, unless you really need it, in your project.json remove `"NUnit.Portable.Agent": "3.4.0-beta-2",`; your code may as well build and test without having the direct dependency on portable agent. :)
