### ISSUE TITLE
cannot exclude categories

### ISSUE THREAD

**Issue by somdoron** [nunit/dotnet-test-nunit#46]
The CI cannot run some of the test, so usually I exclude them in the CI.

However I don't found a way to do it with dotnet test.

**Comment by jasonwilliams200OK** [comment]
Are you marking the tests as explicit? If so then, it should work on CI and command line in general but not when running from VS: https://github.com/nunit/dotnet-test-nunit/issues/25.

**Comment by somdoron** [comment]
No, I only set a category to them. I will use the explicit attribute instead.

Thanks.

**Comment by rprouse** [comment]
You can also add the `--where` command line option from the NUnit console to run/exclude specific tests or categories. See the NUnit console docs for info. Unfortunately `dotnet test` does not show the command line options of the runner even though we provide them :-1:

**Comment by jasonwilliams200OK** [comment]
We can send command line options to process via argument separator `--`; i.e.
 `dotnet test path/to/test/dir -- --where ..`
