### ISSUE TITLE
Find way to hide NUnit.Compatability.Path from intellisense

### ISSUE THREAD

**Issue by jcansdale** [nunit/dotnet-test-nunit#52]
The .NET Core version of `nunit.framework` contains a public class called `Path`. This shows up in intellisense at the top when you try to auto-complete a reference to `Path`. This can be annoying because `Path` is a commonly used class.

![compat](https://cloud.githubusercontent.com/assets/11719160/16804634/a3c3856a-4904-11e6-8f37-00d98200d810.png)

**Comment by rprouse** [comment]
@jcansdale I am pretty sure it is gone in the latest versions on master. It was annoying me to, so I removed it from the compatibility classes in the portable driver because it wasn't really needed. It was left over from when the driver was a PCL.

I just searched the code and can't find it, but I'll leave this open until the next release just in case I'm blind :smile:

**Comment by jcansdale** [comment]
@rprouse,

This was with 'nunit.framework' v3.4.1 (lousy bug report missing that).

Good to hear you're on top of it. :smile:

**Comment by rprouse** [comment]
Ah, that is where it was coming from. Most people won't be including the NUnit.Compatibility namespace when using the PCL, but it should probably be internal anyway. We might also be able to drop it when we switch the PCL to .NET Standard. 

I am going to move this to the main NUnit repo. I am pretty sure it belongs there.

**Comment by rprouse** [comment]
Issue moved to [nunit/nunit #1663](https://github.com/nunit/nunit/issues/1663) via [**ZenHub**](https://www.zenhub.com/)

**Comment by jcansdale** [comment]
> Most people won't be including the NUnit.Compatibility namespace when using the PCL, but it should probably be internal anyway.

The problem is with intellisense, if you don't already have a `using System.IO`. This is compounded by the fact that `System.IO.Path` is in a separate assembly if you're using .NET Core (therefore appears further down the intellisense suggestions).
