### ISSUE TITLE
when labels is set to All no outcome is printed, only test name

### ISSUE THREAD

**Issue by somdoron** [nunit/dotnet-test-nunit#55]
I tracked this down to the XML from the event doesn't include any messages.
In order to solve this for me I changed the  TestExecutionListener.OnTestCase to:

```csharp
        void OnTestCase(XElement xml)
        {
            var testResult = ParseTestResult(xml);

            string output = null;

            if (testResult.Messages.Count > 0)
                output = testResult.Messages[0];
            else if (testResult.Outcome != TestOutcome.None)
                output = testResult.Outcome.ToString();
            

            TestFinished?.Invoke(this, new TestEventArgs(testResult.Test.FullyQualifiedName, output));

            if (Options.DesignTime)
                _sink?.SendTestResult(testResult);
        }
```

I can make a pull request if you want

**Comment by rprouse** [comment]
Fixed by #56

**Comment by rprouse** [comment]
@somdoron would you mind going into NuGet and renaming your dotnet-test-nunit with labels package and add a DEPRECATED into the title so that it is clear to users that it is fixed in the latest official version? Thanks...

**Comment by somdoron** [comment]
@rprouse forgot to update, done :-)

**Comment by rprouse** [comment]
Thanks
