### ISSUE TITLE
NUnit TestResults.xml missing?

### ISSUE THREAD

**Issue by lct005** [nunit/dotnet-test-nunit#61]
I need to load and convert NUnit TestResults.xml to html report. But I cannot find where is the TestResults.xml located.

Here is my project.json setting:

`
"dependencies": {
    "NUnit": "3.4.1",
    "dotnet-test-nunit": "3.4.0-beta-1"
  },

  "testRunner": "nunit",

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dnxcore50"
      ],
      "dependencies": {
        "TestLibrary": { "target": "project" },
        "Microsoft.NETCore.App": {
          "version": "1.0.0-*",
          "type": "platform"
        }
      }
    }
`

**Comment by jasonwilliams200OK** [comment]
TestResults.xml is generated after you run the tests through muxer: `dotnet test` command. It is located in the directory where you executed the said command. For example, if your application is following structure:

```
My Solution Directory
      \
       Project A
      \
       Project B
      \
       Test Project
```

and you run `dotnet test "Test Project"` while being in `My Solution Directory`, then you will get TestResults.xml in `My Solution Directory`. If you are in the `Test Project` directory, then after running the test, you will get the XML report in the test directory and you don't need to specify directory path when running the command (just `dotnet test` without any further argument would do the job).

**Comment by lct005** [comment]
got it now. Many thanks
