### ISSUE TITLE
Unable to resolve dependencies

### ISSUE THREAD

**Issue by Knaackee** [nunit/dotnet-test-nunit#62]
If i create a new .NET Core class library and simply copy the package.json from the readme of this repo 
i cant get it build.

```
{
  "version": "1.0.0-*",

  "dependencies": {
    "dotnet-test-nunit": "3.4.0-beta-1"
  },

  "testRunner": "nunit",

  "frameworks": {
    "netcoreapp1.0": {
      "imports": "portable-net45+win8",
      "dependencies": {
        "Microsoft.NETCore.App": {
          "version": "1.0.0-*",
          "type": "platform"
        }
      }
    }
  }
}

```

```
log  : Restore failed in 817ms.
Errors in Y:\Development\Blazingo\Blazingo\src\Blazingo.Tests\Blazingo.Tests.xproj
    Unable to resolve 'NUnit.Portable.Agent (>= 3.4.0-beta-1)' for '.NETCoreApp,Version=v1.0'.
    Unable to resolve 'Microsoft.DiaSymReader.Native (>= 1.4.0-rc2)' for '.NETCoreApp,Version=v1.0'.
    Unable to resolve 'Microsoft.DiaSymReader (>= 1.0.8)' for '.NETCoreApp,Version=v1.0'.
```

**Comment by rprouse** [comment]
Looks like a NuGet restore issue. Have you tried `dotnet restore` from the command line? I assume you have the final release of .NET Core installed? Network issues?

**Comment by dknaack** [comment]
Ok, `dotnet restore` and `dotnet build` worked from console. But not in Visual Studio 2015 Update 3.
So far, so good. Any ideas ? 

Thanks in advance!

**Comment by rprouse** [comment]
Very weird. I assume that the packages in your main project restore okay? Do you need to update the NuGet extension? Anything in a NuGet.config file in your solution or in any of the locations that it is read from (https://docs.nuget.org/consume/nuget-config-file)?

**Comment by rprouse** [comment]
@dknaack did you make any progress on this issue?

**Comment by rprouse** [comment]
I am closing since we have not heard back from you. If you have more information, add it to this issue and we will reopen.
