### ISSUE TITLE
dotnet-test-nunit not running in debug for asp.net core mvc projects

### ISSUE THREAD

**Issue by jplebre** [nunit/dotnet-test-nunit#63]
As title suggests. I can run tests but cannot debug.

Simple project: 
- 1st project is MVC empty app under Src/MyApp.WebApp.Site,
- 2nd project class Library for test under test/MyApp.WebApp.Tests

Followed the instructions for the project.json:
```JSON
{
    "version": "1.1.0-*",

    "dependencies": {
        "MyApp.WebApp.Site": {
            "target": "project"
        },
        "NUnit": "3.4.1",
        "Microsoft.AspNetCore.TestHost": "1.0.0",
        "dotnet-test-nunit": "3.4.0-beta-1"
    },
    
    "testRunner": "nunit",

    "frameworks": {
        "netcoreapp1.0": {
            "imports": [
                "netcoreapp1.0",
                "portable-net45+win8"
            ],
            "dependencies": {
                "Microsoft.NETCore.App": {
                    "version": "1.0.0-*",
                    "type": "platform"
                }
            }
        }
    }
}
```

And the site's project.json (abridged):
```JSON
{
  "dependencies": {
    "Microsoft.NETCore.App": {
        "version": "1.0.0",
        "type": "platform"
    },
    ...
  },

  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },

    "buildOptions": {
        "emitEntryPoint": true,
        "preserveCompilationContext": true
    },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "web.config"
    ]
  },

  "scripts": {
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}
```

I have a homecontroller with an index and return View();
And I have the following test:
```C#
[Test]
public void IndexMethodLoadsProperly()
{
    var controller = new HomeController();
    var actionResult = (ViewResult)controller.Index();
    Assert.That(actionResult, Is.Not.Null);
    Assert.That(actionResult.ViewName, Is.EqualTo("Index"));
}
```

Test runs and passes, but can't put breakpoints and 'debug' from the test explorer window.
VS goes into "orange" mode but quits without running the tests, with following error:
```
------ Run test started ------
Running tests in 'C:\MyProjects\MyApp\MyApp.WebApp\tests\MyApp.WebApp.Site.Tests\project.json' ["C:\Program Files\dotnet\dotnet.exe" test "C:\MyProjects\MyApp\MyApp.WebApp\tests\MyApp.WebApp.Site.Tests\project.json" --output "C:\MyProjects\MyApp\MyApp.WebApp\tests\MyApp.WebApp.Site.Tests\bin\Debug\netcoreapp1.0" --port 55768 --parentProcessId 6812 --no-build]
No handler for message 'TestRunner.TestCompleted' when at state 'TestExecutionSentTestRunnerProcessStartInfo'
An exception occurred while invoking executor 'executor://dotnetunittestexecutor/v1': Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.
An existing connection was forcibly closed by the remote host
========== Run test finished: 0 run (0:00:02.6558952) ==========
```

not sure exactly how to keep debugging this.... any help?

Cheers

**Comment by jasonwilliams200OK** [comment]
It would be helpful if you create a sample app, zip the solution folder and upload to your first comment (drag drop the zip over the comment box in edit mode, and it will generate a link) or drop in any of the following comment. This quickens our repro process. http://sscce.org :)

@rprouse, should we set up the repo's [contribution guildeline](https://help.github.com/articles/setting-guidelines-for-repository-contributors/) with such directions for future issues?

**Comment by rprouse** [comment]
@jasonwilliams200OK yes we probably should add the contributions guidelines. We could crib off the main NUnit one and adjust for this repo.

**Comment by jplebre** [comment]
Apologise for this: when creating a project to zip it over to you guys couldn't replicate the issue.
I *think* it was because the folder that houses the test projects was called "tests" and the global file had it referenced as "test".

still a bit odd as I figured if the test project references the web app project it should "link them" fine, but I'll scrub this one down to a newb mistake.

I'll close it but if you find it's still an issue I'll zip the project over.

**Comment by jasonwilliams200OK** [comment]
If renaming `test` -> `tests` in global.json fixed the problem for your original project, then that must be the issue and we can conclude that global.json requires correct child projects' names.

All these hidden behaviors will change in the forthcoming version (preview 3) of dotnet-cli, where they are dumping the xproj, project.json etc. in favor of good old XML-based, msbuild-driven csproj with ability to host multiple frameworks and ability to work without specifying every source file in the project (the two major benefits of xproj/project.json).

Note that while .NET Core is RTMd, .NET CLI (the tool) is still in preview so things are pretty broken and one can expect major breaking change as `preview` doesn't warrant long lasting behavior in semver paradigm anyway..

**Comment by jplebre** [comment]
Seems I'm still having intermitent issues with test explorer and running single tests. may zip that file after all. Will play a bit more w it
@jasonwilliams200OK yeah not looking forward to all those changes :)
Thanks for the help!

**Comment by rprouse** [comment]
@jplebre I think we all have intermittent issues running tests in Visual Studio. Since it works for me most of the time and restarting Visual Studio usually fixes the issues I am seeing, I assume the issues are within Visual Studio and the new tooling, not within NUnit. `<head in sand>` :smile:
