### ISSUE TITLE
docs(readme): project.json not aligned with description

### ISSUE THREAD

**Issue by BrainCrumbz** [nunit/dotnet-test-nunit#65]
Hello there

just a note on readme, probably a leftover from alteridem.net post. Text after `project.json` says:

> Note that the `NUnitWithDotNetCoreRC2` dependency is the project under test.

but shown `project.json` example is actually missing that dependency. Not sure how you'd like to change this, so that's why the issue (instead of PR), HTH.

**EDIT**

Also, following paragraph says 

> I also had to add to the imports for both the test adapter and NUnit to resolve.

but actually there seems to be no NUnit import.

Regards

**Comment by rprouse** [comment]
Thanks I will clean it up with the next beta release.
