### ISSUE TITLE
dotnet-test-unit.exe hangs after the tests are completed

### ISSUE THREAD

**Issue by ogreenz** [nunit/dotnet-test-nunit#67]
Hello, I use in my test project dotnet-test-nunit 3.4.0-beta-1, and since it's an .xproj project I use Visual Studio 2015 update 3 unit testing system. after the test is finished the .exe responsible to run the test doesn't finish and still hold handles to my project files denying me to recompile them without forcibly terminating the process.

**Comment by rprouse** [comment]
We shouldn't be holding files open, but in the meantime, make sure **Keep test execution running** is unchecked in Visual Studio.

![image](https://cloud.githubusercontent.com/assets/493828/17463088/f329ed6a-5c8c-11e6-9ae0-6f5ea2da1bee.png)

**Comment by ogreenz** [comment]
Thanks but it only affects the execution engine and not dotnet-test-nunit.exe process.

**Comment by rprouse** [comment]
Is the process running after test exploration, but before running? NUnit gets started to explore the tests and to run them, so it would help to know which is sticking around.

**Comment by ogreenz** [comment]
Sorry I think it was some weird environment issue. you can close this.

**Comment by rprouse** [comment]
Thanks for getting back to us. I see a lot of weird behaviour with the .NET Core tools in Visual Studio that a restart often fixes. Right now I am just chalking it up to the fact that the tools are still preview.
