### ISSUE TITLE
dotnet-test-nunit doesn't run on 32-bit operating systems

### ISSUE THREAD

**Issue by pranavkm** [nunit/dotnet-test-nunit#81]
I was trying out some test runners and noticed that `dotnet-test-nunit 3.4.0-beta-2` doesn't run on x86 operating systems. The test launcher fails like so:

```
Project ConsoleApp1 (.NETFramework,Version=v4.6) will be compiled because inputs were modified
Compiling ConsoleApp1 for .NETFramework,Version=v4.6

Compilation succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:01.2983508

dotnet-test Error: 0 : System.ComponentModel.Win32Exception: The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Microsoft.DotNet.Cli.Utils.Command.Execute()
   at Microsoft.DotNet.Tools.Test.ConsoleTestRunner.DoRunTests(ProjectContext projectContext, DotnetTestParams dotnetTestParams)
   at Microsoft.DotNet.Tools.Test.BaseDotnetTestRunner.RunTests(ProjectContext projectContext, DotnetTestParams dotnetTestParams, BuildWorkspace workspace)
   at Microsoft.DotNet.Tools.Test.TestCommand.DoRun(String[] args)
```

The issue stems from not having runtime specific binaries in the package. For reference, Here's the structure `dotnet-test-xunit` which works fine in this scenario:

```
DOTNET-TEST-XUNIT\2.2.0-PREVIEW2-BUILD1029
├───lib
│   ├───net451
│   │       dotnet-test-xunit.exe
│   │
│   └───netcoreapp1.0
│           dotnet-test-xunit.dll
│           dotnet-test-xunit.runtimeconfig.json
│
└───runtimes
    ├───win7-x64
    │   └───lib
    │       └───net451
    │               dotnet-test-xunit.exe
    │
    └───win7-x86
        └───lib
            └───net451
                    dotnet-test-xunit.exe
```

Unfortunately, `dotnet build` \ `dotnet pack` does not make it easy to produce a package with runtime directories. https://github.com/xunit/dotnet-test-xunit/blob/master/build.ps1#L63-L92 is what xunit does to create the package structure (warning: it's not pretty!)

**Comment by pranavkm** [comment]
I ran into this while working on sign-off work for the October preview release of AspNetCore. So I'm not particularly affected by this. Just thought you might like to know

**Comment by rprouse** [comment]
@pranavkm thanks for the info. I will get the changes into the next update.

**Comment by pranavkm** [comment]
The strategy for tests changed significantly since this was filed. Closing since this isn't super relevant now.
