### ISSUE TITLE
Project with no tests throws failure

### ISSUE THREAD

**Issue by jplebre** [nunit/dotnet-test-nunit#83]
I seem to remember this being discussed somewhere, apologies if it was, but I feel we shouldn't be failing because of this:

![image](https://cloud.githubusercontent.com/assets/5503088/19639769/a94f94e2-99d1-11e6-8b14-ab3fce46e5be.png)

I had to comment the tests out as CI's database is not ready for these tests yet.
Ofc I can take it out of the travis.yml file, btu seems odd

**Comment by rprouse** [comment]
This is standard for NUnit. We assume that if we don't find any tests in an assembly that we were told to run, then there must be something wrong.

As a workaround, add one test with an Assert.Pass() in it.
