### ISSUE TITLE
Adapter not running all tests

### ISSUE THREAD

**Issue by rprouse** [nunit/dotnet-test-nunit#87]
@fredgate commented on [Sat Nov 05 2016](https://github.com/nunit/nunit3-vs-adapter/issues/131#issuecomment-258652416)

I have similar problem with NUnit and Visual Studio 2015 Update 3.

The project.json of my test project :
```
{
	"version": "1.0.0-*",
	"testRunner": "nunit",

	"frameworks": {
		"netcoreapp1.0": {
			"imports": [ "portable-net45+win8" ],
			"dependencies": {
				"Microsoft.NETCore.App": {
					"type": "platform",
					"version": "1.0.1"
				}
			}
		}
	},

	"dependencies": {
		"dotnet-test-nunit": "3.4.0-beta-3",
		"NUnit": "3.5.0",
		"NUnit3TestAdapter": "3.5.1",
		"Moq": "4.6.38-alpha",
		"MyProject.Services.Impl": { "target": "project" }
	}
}
```

I have one class with two tests. They are well discovered and run.
Then I had a another test in the same class. The new test is well discovered. But if in test explorer, I right click on the class, and select Run selected tests, the two old tests are run but the new is not run.
If I close Visual Studio and reopen it, then run all tests of project, then the 3 tests are executed.

Next I add a second class with a fourth test. All the tests appear in Test Explorer, but all in the initial class and the new class does not appear. Then in Test Exlorer, if I click on the class then Execute selected tests, then only 2 tests are executed (one of the two inital, and the third).
Then I close and reopen Visual Studio, and the two classes appear with the four tests. I select the two class and right click Run selected tests, this times the four tests are run.

I had others problem :
- if I delete a class containing some tests, andgroup by class, it appear again in test explorer with tests of another class.
- if I have a second NUnit test project, some tests appear not in the good project in Test Explorer.

If I replace NUnit by xUnit, all work fine (but I will prefer NUnit).

---

@rprouse commented on [Sat Nov 05 2016](https://github.com/nunit/nunit3-vs-adapter/issues/131#issuecomment-258652600)

@fredgate since you are using .NET Core, you only need `dotnet-test-nunit`. Remove `NUnit3TestAdapter`, it currently only runs full framework tests.

What happens if you Run All? Are all tests run?

---

@fredgate commented on [Sat Nov 05 2016](https://github.com/nunit/nunit3-vs-adapter/issues/131#issuecomment-258653167)

At first I had not NUnit3TestAdapter. I added it to see if it can solve the problem. But it changed nothing, so I remove it.

I closed and reopened Visual Studio. I click Run all, and all the 4 tests were run and had the green icon. Then I added two new tests, one in each class. In test explorer the 2 new tests appear, each in the good class. The 2 new tests appear with the blue icon indicating that they are not yet run (it is normal), but two others tests appear also with this blue icon (it is not normal as they had the green icon).
Next I click on Run all; all the 6 tests are run (it is ok).
Next I select the two classes and click Run selected tests : only 5 tests are run (one the 2 first tests is not run).
Next I click again Run All : all the 6 tests are run (it is ok).
Next I select the two classes, and click again Run selected tests : again only 5 tests are run (the same as before).

Next I delete the first test of the second class. In Test Explorer, the 5 remaining tests appear in the correct classes. Next I click Run all : the 5 tests are run. Next I select the two classes and click Run selected tests : only 3 of the 5 tests are run (all in the first class, the remaining test -that is new- in the second class is not run).

---

@CharliePoole commented on [Sat Nov 05 2016](https://github.com/nunit/nunit3-vs-adapter/issues/131#issuecomment-258653489)

@fredgate Can we take the discussion to the repo of the software you are actually using?

**Comment by rprouse** [comment]
@fredgate I have moved your issue to the .NET Core Adapter repo, we can discuss here.

**Comment by fredgate** [comment]
Here is a screenshot of the problem for the last described scenario (I selected the two classes and click Run selected tests) : only 3 of the 5 tests are run.

![temp](https://cloud.githubusercontent.com/assets/3648269/20034702/c78165ee-a3c7-11e6-93f2-95a67f054ca1.png)

**Comment by rprouse** [comment]
Thanks for the detailed report, we will look at it as soon as we can.

**Comment by fredgate** [comment]
Another information. I removed the exprimental tests (the entire FooTests class and Baz* tests of my XxxxServiceTest class). When I rebuild my project, then there is only my two original tests (that is ok), but they do not appear in the correct class : one test is located in the FooTest class while it not longer exists, and the other has the blue icon indicating that it was not run (it was not the case, it should have the green icon).

![temp](https://cloud.githubusercontent.com/assets/3648269/20036771/bc862de2-a411-11e6-8922-ba836aba16d0.png)

If I select the two classes and click Run selected test, only the test in the XxxxServiceTests class is run. If I click Run all tests, the two tests are run. If I close and reopen Visual Studio, everything works again.

**Comment by dougkpowers** [comment]
This is yet another issue with the Guid generation for a test case, and subsequently how changes to tests are negotiated with Visual Studio.  

Turns out, the assembly name and test id is also not sufficient for the generation of a Guid for a test case.  During the discovery process, Visual Studio will not update the internal value for FulluyQualifiedName for a test if the Guid does not change.  Therefore, if you change the values of a TestCase (or the name of a test), and they have the same test IDs across runs, then visual Studio will ignore the new FullyQualifiedName returned during test discovery since the Guid doesn't change.  

While it ignores the new FullyQualifiedName, it will update the DisplayName, which made debugging this very frustrating.  Nonetheless, to force a new Guid, we use the fullname of the testcase in the Guid/signature generation and that seems to solve the problem.  

The following comment (from the[ xunit project](https://github.com/xunit/xunit/blob/master/src/abstractions/xunit.abstractions/TestCases/ITestCase.cs)) does a great job laying out the requirements

> The unique identifier for a test case should be able to discriminate
> among test cases, even those which are varied invocations against the
> same test method (i.e., theories). Ideally, this identifier would remain
> stable until such time as the developer changes some fundamental part
> of the identity (assembly, class name, test name, or test data); however,
> the minimum stability of the identifier must at least extend across
> multiple discoveries of the same test in the same (non-recompiled)
> assembly.

A pull request has been submitted for a fix.  It uses the assembly name plus the test case id plus the fully qualified name of the test to generate a Guid.  By using all three of these values as the input to Guid generation, we should be able to meet the requirements laid out in the comment above.
