### ISSUE TITLE
TxM to be made more relaxed

### ISSUE THREAD

**Issue by jasonwilliams200OK** [nunit/dotnet-test-nunit#9]
Reference links: https://oren.codes/2016/02/08/project-json-all-the-things/ and https://docs.nuget.org/consume/projectjson-format.

File: https://github.com/nunit/dotnet-test-nunit/blob/174b5ea/src/dotnet-test-nunit/project.json.

I think `"net451"` can be lowered to `"net45"`.

and

```json
      "imports": [
        "dnxcore50",
        "dotnet",
        "portable-dnxcore50+net45+win8+wp8+wpa81",
        "portable-net45+win8"
      ],
```

can be reduced to:

```json
      "imports": [
        "portable-net45+win8"
      ],
```

and maybe add "supports" section to ensure the compatibility before hand.

@dagood, @ericstj, @yishaigalatzer can you please confirm whether the above assumption is correct from xplat and greater coverage viewpoint, that is, the lower the x in `net4x` framework is, the more available the package would be; and the less `imports` we have the better it guarantees cross-platform'ness? Also please shed some light on significance of having "supports". :)

**Comment by rprouse** [comment]
I managed to get the imports down to 

```json
      "imports": [
        "dnxcore50",
        "portable-net45+win8"
      ],
```

Both `dotnet-test-mstest` and `dotnet-test-xunit` use `net451`, so I am going to stick with that until someone can confirm otherwise.

**Comment by jasonwilliams200OK** [comment]
@rprouse, what is requiring `dnxcore50`? I just upgraded a project which was requiring `dnxcore50` due to the dependency on Newtonsoft.JSON v8.0.3.  I bumped the version to 9.0 beta, removed `dnxcore50` and it felt really good. :)
Would be nice to avoid anything-dnx down the road.

**Comment by rprouse** [comment]
@jasonwilliams200OK to be honest, I am not sure what was requiring `dnxcore50`. When I removed it, all packages restored, but when I compiled it complained that Object was not defined and that I needed to import mscorlib. To be honest, I was working on other stuff, so didn't spend too much time on it since adding dnxcore50 back in fixed it.

**Comment by jasonwilliams200OK** [comment]
@rprouse, I have prepared a patch to revoke the dependency on dnx:

```diff
--- a/src/dotnet-test-nunit/project.json
+++ b/src/dotnet-test-nunit/project.json
@@ -29,15 +29,19 @@
   "frameworks": {
     "netcoreapp1.0": {
       "imports": [
-        "dnxcore50",
-        "portable-net45+win8"
+        "dotnet5.1"
       ],
       "dependencies": {
         "Microsoft.NETCore.App": {
           "type": "platform",
           "version": "1.0.0-rc2-3002702"
         },
-        "System.ObjectModel": "4.0.12-rc2-24027"
+        "Microsoft.DiaSymReader": "1.0.8-rc2-60418-01",
+        "Newtonsoft.Json": "9.0.1-beta1",
+        "System.Diagnostics.Debug": "4.0.11-rc2-24027",
+        "System.ObjectModel": "4.0.12-rc2-24027",
+        "System.Runtime": "4.1.0-rc2-24027",
+        "System.Runtime.InteropServices": "4.1.0-rc2-24027"
       }
     },
     "net451": {
```

Note that the only reason we have to specify `"dotnet5.1"` and the depnedencies is because of this error:

```sh
Errors in ~/projects/dotnet-test-nunit/src/dotnet-test-nunit/project.json
    Package NUnit.Portable.Agent 3.3.0-CI-2701-PR-1517 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package NUnit.Portable.Agent 3.3.0-CI-2701-PR-1517 supports:
      - dotnet (.NETPlatform,Version=v5.0)
      - portable-monoandroid10+monotouch10+net45+win8+wp8+wpa81+xamarinios10+xamarinmac (.NETPortable,Version=v0.0,Profile=net45+win8+wp8+wpa81+Xamarin.Mac+MonoAndroid10+MonoTouch10+Xamarin.iOS10)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.
```

if you can point me to `NUnit.Portable.Agent` code base, I can prepare a patch for it, so the patch for this repo would be much smaller than that.

**Comment by rprouse** [comment]
@jasonwilliams200OK The `NUnit.Portable.Agent` shares a lot of code with the main NUnit engine, so it is in the same repo. I am still waiting to merge the PR, so it is on branch i`ssue-1371`

It is a PCL project so that I can use it in the Xamarin runner. The code is at https://github.com/nunit/nunit/tree/issue-1371/src/NUnitEngine/Portable/nunit.portable.agent but it is part of the main NUnit.sln in the root of the repo.

The nuspec for it is at https://github.com/nunit/nunit/blob/issue-1371/nuget/engine/nunit.portable.agent.nuspec

I am going to try to get that PR nunit/nunit#1517 merged today. Were you thinking about doing a pull request or just posting a patch? If a PR, you may want to wait to do it off master after I merge nunit/nunit#1517. If you were thinking a patch, I will hold off merging and add it into that PR.

**Comment by jasonwilliams200OK** [comment]
Thanks @rprouse, I will try to make a patch now so it can be shipped with the ready PR. :)

**Comment by jasonwilliams200OK** [comment]
@rprouse, can you tell me how are you building the project.json? It seems like `dotnet build` doesn't build anything.

I have prepared this patch to remove the extra stuff: https://gist.github.com/jasonwilliams200OK/5ca437ec46fd2ad9a8abc63f282a3c71, save in a file say `nukednx.diff` then `git apply nugednx.diff` in the project repo followed by `git rm *.lock.json`.

Please let me know how project.json builds, so i can handpick the correct RC2 dependencies for the project.

**Comment by rprouse** [comment]
@jasonwilliams200OK those `project.json` files are stale code that is left over from our initial attempts to port to .NET Core. I have entered an issue to remove them. Sorry that they confused you.

Our current projects are straight `csproj` style PCL projects. This project uses the `nunit.portable.agent` project and the NUnit framework portable build is the `nunit.framework-portable` project. NuGet packages are created using `nuspec` files in the `nuget` root folder.

If you open the `nunit.sln`, the two projects and nuspec's are here;

![image](https://cloud.githubusercontent.com/assets/493828/15749734/6de0f0ea-28b1-11e6-8831-8e9cce7ac0d0.png)

We build and test from the command line using Cake Build. Most common targets are;

```
.\build.ps1 -Target Build
.\build.ps1 -Target TestAll
.\build.ps1 -Target PackageNuGet
```

**Comment by jasonwilliams200OK** [comment]
@rprouse, thanks for the info. If we instead have those projects as xproj  (like this project is using: https://github.com/xunit/dotnet-test-xunit xproj which is good, also there is no dnxcore in their json imports: https://github.com/xunit/dotnet-test-xunit/blob/5d3bd7d/test/dotnet-test-xunit.Tests/project.json), then it would be much easier to specify the target frameworks PCL and NetCore in project.sjon. Otherwise all consumers targeting nunit would need to import dnxcore50 and on Unix, we would have dependency on Mono PCL reference assemblies which is something nobody is going to like IMO.

If replacing `nunit.portable.agent.csproj` and `nunit-framework.portable.agent.csproj` with their xproj variants is a viable option for `nunit.sln`, I can prepare a pull request for nunit.

**Comment by rprouse** [comment]
@jasonwilliams200OK so a PCL project that targets `ASP.NET Core 1.0` isn't good enough? That is a bit disappointing. I was hoping it would be as simple as dropping the compiled binary in the right target folder in NuGet.

I am open to a pull request, but I see a few issues with the `xproj` approach.

1. We like to be able to build the solution in older versions of Visual Studio and in MonoDevelop on Linux. I assume that won't be possible?
2. Will the portable assembly created still be able to target Win8, Xamarin, WinPhone, etc?
3. When I originally tried creating a .NET Core version of the framework, I could not have an `xproj` in the same directory as the `csproj` files that target the other versions of the framework (2.0, 3.5, CF, SL50, etc). Is that still the case?
4. The NuGet packages that are created still need to include all of the other frameworks built from the other `csproj` projects. Can we just build the `xproj` and package it using the existing NuSpec?
5. I assume all of the portable test projects and the portable NUnitLite project will need to be converted?
6. I am also concerned about switching those projects to `xproj` when it has been announced that .NET Core will be going back to `csproj` after the release.

Until everything is sorted out, isn't it easier to ask our users to take on a few extra dependencies in their test projects until .NET Core settles? We were also considering creating a full .NET Core version of the NUnit framework (in addition to the PCL) after the 3.4 release. I want to do things properly and I want to support .NET Core, but we also need to maintain compatibility with other framework targets.

If we decide to go forward with this and it limits us to Visual Studio 2015+, then I need to discuss with the rest of the team.

**Comment by jasonwilliams200OK** [comment]
@rprouse,

We can have `nunit.netstandard.sln` with extra xproj and project.json files in each directory. This way we would just need to pack all the dlls in the one place and rest of the process would be isolated.. just run msbuild twice: `msbuild nunit.sln && msbuild nunit.netstandard.sln`.

As far as I have experienced, we can (now?) have xproj and csproj exist in same directory.

**Comment by jasonwilliams200OK** [comment]
I read somewhere that in next version of VS, the process will be streamlined in a way that when we open the solution with xproj in it, it will be converted to the new kind of csproj. That upcoming csproj will have all the good bits of xproj (like black-listing of compile targets instead of explicitly specifying each .cs/.vb file etc.). At that point, we would just remove the xprojs, project.jsons and this extra .sln (`nunit.netstandard.sln`) file and converge to one csproj, which would be able to target multiple versions of framework. At this point that doesn't exist. CoreFX repo is doing similar kind of thing using buildtools i guess, but that is something which isn't ready for our usage.

**Comment by rprouse** [comment]
If we are going to create a separate solution, then I think we should just target .NET Core with it and maybe remove .NET core from the PCL? It would be fairly straightforward if we can duplicate the defines in the current PCL project, mainly PORTABLE I think.

@CharliePoole what do you think about this approach? I don't like to introduce another solution, but the alternative is to require VS2015 to build. An alternative is to accept that and add to the nunit.sln, but not to the nunit-linux.sln.

**Comment by CharliePoole** [comment]
@rprouse It sounds reasonable at least for the time being if you want to move ahead. As you know, I'm typically more inclined to let Microsoft stabilize their stuff before supporting it, but I guess a lot of people want this, so let's keep it reasonably separate for now.

**Comment by rprouse** [comment]
Okay, let's go for a separate solution for now. We can merge into the main solution later if necessary.

I think there will be some back and forth on this, so it might be easiest if the PR was on a branch in the main repo so I can help. @jasonwilliams200OK if you want to create the PR, I will add you as an NUnit contributor so you don't have to fork and I can add to your branch. Is that okay?

**Comment by rprouse** [comment]
@jasonwilliams200OK I made you a contributor to the NUnit project if you want to push your branch directly to the main repo. If you do that, I can help out by pushing changes to the branch.

**Comment by jasonwilliams200OK** [comment]
@rprouse, thanks!
I have prepared a patch jasonwilliams200OK/nunit@630a616 in my fork's master branch.

Clone: `git clone https://github.com/jasonwilliams200ok/nunit j-nunit`

On Windows you can test it with three ways:

1. Open `j-nunit/nunit.netstandard.sln` in VS2015 with dotnet cli preview 1 installed and build.
2. From command line with dotnet cli preview 1 installed and msbuild (/version >= 14) in path, `cd j-nunit` then `dotnet restore` and finally `msbuild .\nunit.netstandard.sln`.
3. From command line with dotnet cli preview 1 installed (only), `cd j-nunit` then `dotnet restore` and explicitly build the two projects that sln contains: `dotnet build src\NetStandard\NunitEngine` and `dotnet build src\NetStandard\NunitFramework`.

From Unix (tested on OS X 10.11 and Ubuntu 14 LTS) with no mono installed, just dotnet cli (https://www.microsoft.com/net/core):

```sh
git clone https://github.com/jasonwilliams200ok/nunit j-nunit && cd j-nunit
dotnet restore
dotnet build src/NetStandard/NunitEngine
dotnet build src/NetStandard/NunitFramework
```

> My favorite batch command which I kept using and which works on both Unix and PowerShell is:
```sh
cd j-nunit;rm -rf ../.nuget;git clean -xdf;dotnet restore --no-cache;dotnet build src/NetStandard/NunitEngine/;dotnet build src/NetStandard/NunitFramework/
```
By removing ~/.nuget and restore with `--no-cache` makes sure that the package restored is the bare bunch which compiler needs to compile this code.
There were cases with other projects when locally everything was building on Windows but our CI system was complaining about missing packages. That's why I trust this "hammer solution".

The produced assembly has zero dependencies on PCL etc. and once available via nuget, consumers targeting netstandrd or even multi-framework won't need to add `imports` section in project.json.

On package-time, the pack script would need to include these assemblies at appropriate location.

**Comment by rprouse** [comment]
@jasonwilliams200OK is there anything else to do in this project for this issue? I believe the only thing outstanding is to create a `netstandard` version of the NUnit Framework.

**Comment by jasonwilliams200OK** [comment]
@rprouse, true the only thing required is netstandard of NUnit Framework. Should we track it with this issue until we get the framework upgraded and bump the version in runner's manifest?

**Comment by rprouse** [comment]
The framework issue is tracked by nunit/nunit#1661. This project does not reference NUnit in its released NuGet packages, only in the tests, so I am going to close this here.
