### ISSUE TITLE
Tests do not run with VS2017 RC

### ISSUE THREAD

**Issue by Snipx** [nunit/dotnet-test-nunit#98]
Hi,
Thanks for building this great tool.

It does not work, however, in my VS2017 Preview (latest version 15.0.26014.0)

My test project looks like the following:
```
<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="**\*.cs" />
    <EmbeddedResource Include="**\*.resx" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="dotnet-test-nunit" Version="3.4.0-beta-3" />
    <PackageReference Include="Microsoft.NETCore.App" Version="1.0.1" />
    <PackageReference Include="Microsoft.TestPlatform.TestHost" Version="15.0.0-preview-20170106-08" />
    <PackageReference Include="NUnit" Version="3.6.0" />
  </ItemGroup>
</Project>
```

I have a single test in the project:

```
using System;
using System.Collections.Generic;
using System.Text;
using NUnit.Framework;

namespace ConsoleApp1
{
    class Test
    {
        [Test]
        public void test() {
            Assert.AreEqual(5, 4);
        }

        public static void Main(String[] args) {
            
        }
    }
}
```

And I try to run the tests with `dotnet test .\ConsoleApp1\ConsoleApp1.csproj`

The output I get:

```
Build started, please wait...
C:\Program Files\dotnet\sdk\1.0.0-preview4-004233\Microsoft.Common.CurrentVersion.targets(1909,5): warning MSB3277: Found conflicts between different versions of the same dependent assembly that could not be resolved.  These reference conflicts are listed in the build log when log verbosity is set to detailed. [C:\users\alexey\documents\visual studio 2017\Projects\ConsoleApp1\ConsoleApp1\ConsoleApp1.csproj]
Build completed.

Test run for C:\users\alexey\documents\visual studio 2017\Projects\ConsoleApp1\ConsoleApp1\bin\Debug\netcoreapp1.0\ConsoleApp1.dll(.NETCoreApp,Version=v1.0)
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
```

The tests do not run at all.
I notice this message about unresolved conflicts, and with some arbitrary dependency manipulations I once was able to get rid of that warning, but that didn't help to run the tests anyway.

Am I doing something wrong or is it a bug?

**Comment by rprouse** [comment]
@Snipx  You aren't doing anything wrong. With the change to CSPROJ/MSBUILD, support for the various `dotnet-test-*` style runners has been dropped. We need to update the old VS Adapter to support .NET Core, but have not finished that work yet.

For now, I would suggest creating an NUnitLite style runner for your tests. Sorry.

**Comment by Snipx** [comment]
@rprouse Thanks a lot, I'll try with NUnitLite. 
Do you have any plans to support running .NET Core/.NET Standard tests with Console Runner? Or maybe it is already supported?

Right now the problem I faced was that the a .NET Standard library output folder does not contain NuGet library dependencies when built. I needed to copy all the dependencies but I couldn't manage to finish the process of resolving all the dependencies. 
I went on to create an issue in `dotnet` community scope, but the advised me to try with `dotnet test`. It turns out currently `dotnet test` is not available with NUnit, but are there any other ways to run tests apart from NUnitLite?

Sorry if it's not the right place to ask this question.

**Comment by rprouse** [comment]
`dotnet test` is supported with NUnit, just not with the new CSPROJ based .NET Core tests (VS2017), only with the XPROJ/project.json based projects (VS2015). With those tests, NUnitLite is the only solution right now, but we are trying to get .NET Core tests running in the console and the adapter soon.

**Comment by Snipx** [comment]
Thanks for the quick and clear answers! I am closing the issue as the problems are known to you and you are working on it.
Good luck with the development and thanks again.

**Comment by rahulpandey8920** [comment]
Hi @rprouse 

Any updates on this please ?

Thanks.
